data_dir: ./cmn-eng-simple
output_dir: ./runs_transformer_cuda
mode: train
run_tag: v3_char_rdrop
seed: 42
device: cuda

epochs: 60
batch_size: 96
eval_batch_size: 128
num_workers: 2
max_src_len: 64
max_tgt_len: 96
max_train_batches: 0
max_eval_batches: 0
max_bleu_samples: 160
checkpoint: ""

d_model: 256
nhead: 8
num_encoder_layers: 4
num_decoder_layers: 4
dim_feedforward: 1024
dropout: 0.15
no_tie_embeddings: false

weight_decay: 0.0001
label_smoothing: 0.15
grad_clip: 1.0
lr_factor: 0.8
warmup_steps: 2000
patience: 12
early_stop_min_delta: 0.02
loss_explosion_ratio: 2.0
loss_explosion_patience: 3

beam_size: 5
beam_alpha: 0.6
max_decode_len: 64
no_repeat_ngram_size: 3

no_amp: false
word_dropout: 0.05
rdrop_alpha: 3.0
run_test_after_train: true
top_k_checkpoints: 5
test_split: test
